name: macfarlan.net
favicon: null
layout_spectrum: 0.11989
typography_spectrum: 0.7898404
title: gather the clan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#ffeacf'
    - '#9ec7dd'
    - '#5d4e49'
    - '#549dd9'
  brandStrength: 0.599916
  lightness: 0.1983583
  saturation: 0.8973449
  rhythmicContrast: 0.1672387
purpose: []
